#!/usr/bin/env bash
set -Eeuo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib-bootstrap.sh"

force="false"

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --force)
      force="true"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

env_file="${app_dir}/.env"

require_file_absent_or_force "${env_file}" "${force}"

auth_secret="$(generate_urlsafe_secret)"
client_secret="$(generate_urlsafe_secret)"

cat <<EOF > "${env_file}"
# Generated by scripts/bootstrap-local.sh
DATABASE_URL=postgres://catastrophic_club:catastrophic_club@127.0.0.1:5432/catastrophic_club
DATABASE_SSL=false
AUTH_SECRET=${auth_secret}
AUTH_SESSION_TTL_SECONDS=604800
KEYCLOAK_BASE_URL=http://localhost:8080
KEYCLOAK_REALM=catastrophic-club
KEYCLOAK_CLIENT_ID=catastrophic-club-web
KEYCLOAK_CLIENT_SECRET=${client_secret}
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_SCOPE=openid profile email
KEYCLOAK_ADMIN_REALM=master
KEYCLOAK_ADMIN_CLIENT_ID=admin-cli
AUTO_RUN_MIGRATIONS=false
AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
AUTH_RATE_LIMIT_WINDOW_SECONDS=60
EOF

echo "Wrote ${env_file}"

cd "${app_dir}"

docker compose -f docker-compose.local.yml up -d
wait_for_http "http://127.0.0.1:8080"

./scripts/configure-keycloak.sh --local --env-file "${env_file}"
npm run db:migrate

cat <<EOF

Local bootstrap complete.

Next steps:
- run: npm run dev
- open: http://localhost:3000
- optional admin console: http://localhost:8080
EOF
