#!/usr/bin/env bash
set -Eeuo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib-bootstrap.sh"

app_domain=""
keycloak_hostname=""
env_file="${app_dir}/../env/app.env"
force="false"
skip_deploy="false"

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --app-domain)
      app_domain="$2"
      shift 2
      ;;
    --keycloak-hostname)
      keycloak_hostname="$2"
      shift 2
      ;;
    --env-file)
      env_file="$2"
      shift 2
      ;;
    --force)
      force="true"
      shift
      ;;
    --skip-deploy)
      skip_deploy="true"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${app_domain}" || -z "${keycloak_hostname}" ]]; then
  echo "Usage: ./scripts/bootstrap-prod.sh --app-domain example.com --keycloak-hostname auth.example.com [--env-file /path/to/app.env] [--force] [--skip-deploy]" >&2
  exit 1
fi

mkdir -p "$(dirname -- "${env_file}")"
require_file_absent_or_force "${env_file}" "${force}"

postgres_superpassword="$(generate_password)"
app_db_password="$(generate_password)"
keycloak_db_password="$(generate_password)"
auth_secret="$(generate_urlsafe_secret)"
client_secret="$(generate_urlsafe_secret)"
admin_password="$(generate_password)"

cat <<EOF > "${env_file}"
# Generated by scripts/bootstrap-prod.sh
APP_DOMAIN=${app_domain}
KEYCLOAK_HOSTNAME=${keycloak_hostname}

POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERPASSWORD=${postgres_superpassword}

APP_DB_NAME=catastrophic_club
APP_DB_USER=catastrophic_club
APP_DB_PASSWORD=${app_db_password}

KEYCLOAK_DB_NAME=keycloak
KEYCLOAK_DB_USER=keycloak
KEYCLOAK_DB_PASSWORD=${keycloak_db_password}

DATABASE_SSL=false
AUTO_RUN_MIGRATIONS=false

AUTH_SECRET=${auth_secret}
AUTH_SESSION_TTL_SECONDS=604800

KEYCLOAK_REALM=catastrophic-club
KEYCLOAK_CLIENT_ID=catastrophic-club-web
KEYCLOAK_CLIENT_SECRET=${client_secret}
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=${admin_password}

AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
AUTH_RATE_LIMIT_WINDOW_SECONDS=60
EOF

echo "Wrote ${env_file}"

if [[ "${skip_deploy}" == "true" ]]; then
  cat <<EOF

Production env bootstrap complete.

Next steps:
- review ${env_file}
- run: ENV_FILE=${env_file} ./scripts/deploy-prod.sh
- run: ENV_FILE=${env_file} ./scripts/configure-keycloak.sh --prod --env-file ${env_file}
EOF
  exit 0
fi

cd "${app_dir}"

ENV_FILE="${env_file}" ./scripts/deploy-prod.sh
ENV_FILE="${env_file}" ./scripts/configure-keycloak.sh --prod --env-file "${env_file}"
ENV_FILE="${env_file}" ./scripts/check-prod.sh

cat <<EOF

Production bootstrap complete.

Manual follow-up:
- verify reverse proxy and TLS for https://${app_domain}
- sign in to the app and test registration/login/logout/favorites/battles/leaderboard
EOF
